[0m11:39:09.158309 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7180c7fa8650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7180c99e9490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7180c8df9b50>]}


============================== 11:39:09.163499 | 722cfd42-74c5-441f-b239-401729448f7f ==============================
[0m11:39:09.163499 [info ] [MainThread]: Running with dbt=1.9.0
[0m11:39:09.164157 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/mnt/c/Users/Waslap/Documents/Repos/igaming-demo/transformations/dbt_project', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt run', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m11:39:09.164857 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /mnt/c/Users/Waslap/Documents/Repos/igaming-demo/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:39:09.166354 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.040870033, "process_in_blocks": "49424", "process_kernel_time": 0.161393, "process_mem_max_rss": "92792", "process_out_blocks": "0", "process_user_time": 0.678679}
[0m11:39:09.166879 [debug] [MainThread]: Command `dbt run` failed at 11:39:09.166813 after 0.04 seconds
[0m11:39:09.167351 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7180c79eede0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7180cb543620>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7180c7fa8650>]}
[0m11:39:09.167802 [debug] [MainThread]: Flushing usage events
[0m11:39:10.210416 [debug] [MainThread]: An error was encountered while trying to flush usage events
